name: clone_mrt_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  url_launcher: ^5.7.2
  flutter_staggered_grid_view: "^0.3.2"
  gradient_text: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/dummy_image.png
    - assets/dummy_live_camera.png
    - assets/dummy_cat.png
    - assets/dummy_dog.png
    - assets/dummy_cat_43.png
    - assets/dummy_cat_11.png
    - assets/dummy_broadcast.png
    - assets/dummy_shop_info.png
    - assets/dummy_gourme_info.png
    - assets/weather_caption.png
    - assets/usage.png
    - assets/weather/sunny.png
    - assets/weather/cloudy.png
    - assets/weather/rainy.png
    - assets/apply_post/dummy_apply_scoop.png
    - assets/apply_post/dummy_apply_special.png
    - assets/apply_post/dummy_apply_campaign.png
    - assets/apply_post/dummy_apply_tv.png
    - assets/apply_post/dummy_apply_radio.png
    - assets/apply_post/dummy_apply_wakemon.png
    - assets/apply_post/dummy_apply_asatoku.png
    - assets/apply_post/dummy_apply_next.png
    - assets/apply_post/dummy_apply_uchinoko.png
